version: '3.1'
services:
  db:
    restart: always
    image: percona/percona-server:${MYSQL_TAG}
    container_name: db
    logging:
  #      driver: none
         driver: "json-file"
         options:
             max-size: "10m"
             max-file: "10"
  #  command: 
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      # - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-utest", "-pgateway*2022"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  api:
    restart: always
    build:
      context: ./api
    image: api:${API_VERSION}
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: ${NODE_ENV}
      API_KEY: ${API_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "3000"]
      interval: 10s
      start_period: 180s
      retries: 20
    depends_on:
      - db
  frontend:
    restart: always
    build:
      context: ./frontend
    image: frontend:${FRONT_VERSION}
    container_name: frontend
    ports:
      - 80:80
    environment:
      NODE_ENV: ${NODE_ENV}
      API_KEY: ${API_KEY}
  